// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndJGma3q3BP1D1CcDqDPRiC5E6lQrlwY',
    appId: '1:699601175216:web:0f9d4b3d979aae6ad6b175',
    messagingSenderId: '699601175216',
    projectId: 'pnotes-596',
    authDomain: 'pnotes-596.firebaseapp.com',
    storageBucket: 'pnotes-596.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5TS-zBJDy2ZXzIeSKmbRsd5SbFChcues',
    appId: '1:699601175216:android:d828f80631948414d6b175',
    messagingSenderId: '699601175216',
    projectId: 'pnotes-596',
    storageBucket: 'pnotes-596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3JvlFhbKoGebrJPsENJYiO1qkzVfJPM',
    appId: '1:699601175216:ios:29bc7ba36a84575ad6b175',
    messagingSenderId: '699601175216',
    projectId: 'pnotes-596',
    storageBucket: 'pnotes-596.appspot.com',
    iosBundleId: 'com.colld.pnotes',
  );
}
